import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

/**
 * A redux toolkit API slice that is used to fetch the about content. In this case,
 * the app hosts the content in a public markdown file. This stores the entire
 * about content as a string (not json). This string is then parsed by the ReactMarkdown
 * component.
 */
export const aboutApiSlice = createApi({
    reducerPath: 'aboutApi',
    baseQuery: fetchBaseQuery({ baseUrl: '/' }),
    endpoints: (builder) => ({

        getAboutContent: builder.query({
            query: () => ({
                url: `/info.md`,
                responseHandler: 'text'
            })
        })
    })
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetAboutContentQuery, useLazyGetAboutContentQuery } = aboutApiSlice;