import { PayloadAction, createSlice } from '@reduxjs/toolkit';
import { HistoryState, Movie } from 'utils/types';

const initialHistoryState: HistoryState = {
    historyItems: {}
};

/** A state slice used to maintain the users viewing history. The state object uses
 * the unique imdb ID as a eky to hold the Movie object. We create reducers to add/edit/delete
 * Movies from the viewing history. Redux toolkit will automatically generate the actions
 * that we need.
 */
const historySlice = createSlice({
    name: 'history',
    initialState: initialHistoryState,
    reducers: {
        addedToHistory: (state, { payload }: PayloadAction<Movie>) => {
            state.historyItems[payload.imdbID] =  payload;
        },
        updatedInHistory: (state, { payload }: PayloadAction<Movie>) => {
            state.historyItems[payload.imdbID] = payload;
        },
        deletedFromHistory: (state, { payload }: PayloadAction<string>) => {
            delete state.historyItems[payload];
        }
    }
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { addedToHistory, updatedInHistory, deletedFromHistory } = historySlice.actions;

export default historySlice;