import { createSlice } from '@reduxjs/toolkit';
import { LayoutState } from 'utils/types';

const initialLayoutState: LayoutState = {
    sidePanelOpen: true
};

/**
 * This portion of the state is used to control the layout of the app. For a simple
 * app such as this, the only requirement is to keep track of whether the side panel
 * (only in mobile view) is open or closed.
 */
const layoutSlice = createSlice({
    name: 'layout',
    initialState: initialLayoutState,
    reducers: {
        sidePanelOpened: (state) => {
            state.sidePanelOpen = true;
        },
        sidePanelClosed: (state) => {
            state.sidePanelOpen = false;
        },
        sidePanelToggled: (state) => {
            state.sidePanelOpen = !state.sidePanelOpen;
        }
    }
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { sidePanelOpened, sidePanelClosed, sidePanelToggled } = layoutSlice.actions;

export default layoutSlice;