import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
import MovieFactory from 'model/MovieFactory';
import { MovieResponse } from 'utils/types';

const apiKey = 'eb143593';

/**
 * A redux toolkit API slice that is used to fetch the Movie. The getMovieByName endpoint
 * is used by the Search Page. The getMovieById endpoint is used by the Movie Details component
 * and fetches the movie based on it's unique imdb ID.
 */
export const movieApiSlice = createApi({
    reducerPath: 'movieApi',
    baseQuery: fetchBaseQuery({ baseUrl: 'https://www.omdbapi.com/' }),
    endpoints: (builder) => ({

        getMovieById: builder.query({
            query: (searchId) => `?i=${searchId}&apikey=${apiKey}`,
            transformResponse: (response: MovieResponse) => {
                return MovieFactory.parseResponse(response);
            }
        }),
        getMovieByName: builder.query({
            query: (searchName) => `?t=${searchName}&apikey=${apiKey}`,
            transformResponse: (response: MovieResponse) => {
                return MovieFactory.parseResponse(response);
            }
        })
    }),
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetMovieByIdQuery, useLazyGetMovieByNameQuery } = movieApiSlice;