import { createSlice } from '@reduxjs/toolkit';
import { MovieState } from 'utils/types';

const initialMovieState: MovieState = {
    searchValue: ''
};

/**
 * Used to maintain the string value that the user searched for.
 * This allows it to be easily shared across components. The Search Results component can
 * use a hook to listen for changes in this state, and react accordingly.
 */
const movieSlice = createSlice({
    name: 'movie',
    initialState: initialMovieState,
    reducers: {
        movieSearched: (state, { payload }) => {
            state.searchValue = payload;
        }
    }
});

// Redux actions automatically generated by redux toolkit 
export const { movieSearched } = movieSlice.actions;

export default movieSlice;