import { PayloadAction, createSlice } from '@reduxjs/toolkit';
import { Review, ReviewState } from 'utils/types';

const initialReviewState: ReviewState = {
    reviewItems: {}
};

/**
 * Maintain the state of the user reviews. The reviews are stored in a an object that uses
 * the unique imdb ID as a key for the review (which contains rating and comment).
 */
const reviewSlice = createSlice({
    name: 'review',
    initialState: initialReviewState,
    reducers: {
        addedToReviews: (state, { payload }: PayloadAction<Review>) => {
            state.reviewItems[payload.imdbID] =  payload;
        },
        updatedInReviews: (state, { payload }: PayloadAction<Review>) => {
            state.reviewItems[payload.imdbID] = payload;
        },
        deletedFromReviews: (state, { payload }: PayloadAction<string>) => {
            delete state.reviewItems[payload];
        }
    }
});

// Redux actions automatically generated by redux toolkit 
export const { addedToReviews, updatedInReviews, deletedFromReviews } = reviewSlice.actions;

export default reviewSlice;